def skipRemainingStages = true

pipeline {
    agent any

    triggers {
        // GitLab Webhook을 통해 backend 브랜치로의 push 이벤트 시 트리거
        gitlab(
            triggerOnPush: true,
        )
    }

    environment {
        USER_PORT = '8080'
        DOCKER_USERINFO = credentials('DOCKER_USER')
        DOCKER_REPO = credentials('DOCKER_REPO')
        EC2_IP = credentials('EC2_SERVER2_IP')
        SSH_INFO = credentials('EC2_SERVER2_SSH')
    }

    stages {

        stage('Checkout Code') {
            steps {
                // backend 브랜치의 feed 폴더만 체크아웃
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/backend']],
                    userRemoteConfigs: [[
                        url: 'https://lab.ssafy.com/s11-bigdata-dist-sub1/S11P21C205.git',
                        credentialsId: 'PERSONAL_ACCESS_TOKEN'
                    ]],
                    extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'feed/']]]]
                ])
            }
        }

        stage('Build Docker Image') {
            when {
                changeset "backend/feed/**"
            }
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'SPRING_JWT_SECRET', variable: 'SPRING_JWT_SECRET'),
                    ])
                    {
                        skipRemainingStages = false
                        sh """
                        cd backend/feed
                        chmod +x ./gradlew
                        ./gradlew build
                        ls build/libs
                        docker build \
                        --build-arg SPRING_JWT_SECRET=${SPRING_JWT_SECRET} \
                        -t feed:latest .
                        """
                    }
                }
            }
        }

        stage('Login to Docker Registry') {
            when {
                changeset "backend/feed/**"
            }
            steps {
                script {
                    sh """
                    docker login -u $DOCKER_USERINFO_USR -p $DOCKER_USERINFO_PSW
                    """
                }
            }
        }

        stage('Push Docker Image to Repository') {
            when {
                changeset "backend/feed/**"
            }
            steps {
                script {
                    sh """
                    docker tag feed:latest $DOCKER_REPO_USR/$DOCKER_REPO_PSW:feed-latest
                    docker push $DOCKER_REPO_USR/$DOCKER_REPO_PSW:feed-latest
                    """
                }
            }
        }

        stage('Deploy to EC2') {
            when {
                changeset "backend/feed/**"
            }
            steps {
                script {
                    withCredentials([
                         string(credentialsId: 'SPRING_JWT_SECRET', variable: 'SPRING_JWT_SECRET'),
                    ])
                    {
                        sh """
                        ssh -o StrictHostKeyChecking=no -i $SSH_INFO $SSH_INFO_USR@$EC2_IP <<-EOF
                        export SPRING_JWT_SECRET=${SPRING_JWT_SECRET}
                        docker stop feed || true
                        docker rm feed || true
                        docker rmi $DOCKER_REPO_USR/$DOCKER_REPO_PSW:feed-latest || true
                        docker system prune -f --volumes
                        docker pull $DOCKER_REPO_USR/$DOCKER_REPO_PSW:feed-latest
                        docker run -it -d --name feed -p $USER_PORT:$USER_PORT \
                        -v /home/ubuntu/VS_photo:/app/photos \  # 볼륨 마운트 추가
                        -e SPRING_JWT_SECRET=${SPRING_JWT_SECRET} \
                        $DOCKER_REPO_USR/$DOCKER_REPO_PSW:feed-latest
                        EOF
                        """.stripIndent()
                    }
                }
            }
        }

        stage('Logout from Docker Registry') {
            when {
                changeset "backend/feed/**"
            }
            steps {
                script {
                    sh """
                    docker logout
                    """
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished!'
        }
        success {
            script{
                if (skipRemainingStages) {
                    echo "No changes in feed folder, skipping build and deploy."
                } else {
                    echo "Deployed successfully on port ${USER_PORT}!"
                    def user = sh(script: 'git log -1 --pretty=format:"%an"', returnStdout: true).trim()
                    mattermostSend (
                        color: 'good',
                        message: "${user}님의 ${env.JOB_NAME} 서버 배포 성공. (#${env.BUILD_NUMBER}) ",
                    )
                }
            }
        }
        failure {
            echo 'Deployment failed!'
            script{
                def user = sh(script: 'git log -1 --pretty=format:"%an"', returnStdout: true).trim()
                mattermostSend (
                    color: 'danger',
                    message: "${user}님? ${env.JOB_NAME} 서버 터졌는데요? (#${env.BUILD_NUMBER}) ",
                )
            }
        }
    }
}
